name: frontend

services:
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: on-failure
    networks:
      - caddy
    labels:
      caddy: localhost
      caddy.header_0: Cross-Origin-Embedder-Policy require-corp
      caddy.header_1: Cross-Origin-Opener-Policy same-origin
      caddy.reverse_proxy: '{{upstreams 3001}}'

networks:
  caddy:
    external: true
