import type { FC } from 'react';
import Head from 'next/head';

const Landing: FC = () => {
  return (
    <>
      <Head>
        <title>Landing</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
    </>
  );
};

export default Landing;
